version: 2

# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
# for Dependabot config documentation
updates:

    # atm-cli crate dependencies
  - package-ecosystem: "cargo"
    directory: "/src/atm-cli/"
    schedule:
      interval: "weekly"

    # libatm crate dependencies
  - package-ecosystem: "cargo"
    directory: "/src/libatm/"
    schedule:
      interval: "weekly"

    # Build container
  - package-ecosystem: "docker"
    directory: "/build-support/docker/"
    schedule:
      interval: "weekly"

    # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
