version: 2

# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
# for Dependabot config documentation
updates:

    # Project dependencies
  - package-ecosystem: "cargo"
    # Directory containing Cargo.toml and Cargo.lock files
    directory: "/"
    # Schedule to run Dependabot
    # Change the interval to "daily" for important projects
    # with larger user bases
    schedule:
      interval: "weekly"

    # Build container
  - package-ecosystem: "docker"
    directory: "/build-support/docker/"
    schedule:
      interval: "weekly"

    # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
