name: Auto-merge Dependabot PRs
on:
  pull_request:
    branches:
      - "dependabot/**"
  workflow_dispatch:

jobs:

  dependabot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      pull-requests: write
    steps:

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install Docker (BuildX)
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests and check code
        shell: bash
        run: |
          if [ -d "src/" ] && [ -z "$(find src/ -maxdepth 0 -empty -type d)" ]
          then
            ./run.sh build
          fi

      - name: Build documentation
        shell: bash
        run: |
          if [ -d "src/" ] && [ -z "$(find src/ -maxdepth 0 -empty -type d)" ]
          then
            ./run.sh make-docs
          fi

      - name: Approve the PR
        run: gh pr review --approve "${PR_URL}"
        env:
          PR_URL: "${{github.event.pull_request.html_url}}"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"

      - name: Auto-merge the PR
        run: gh pr merge --auto --merge "${PR_URL}"
        env:
          PR_URL: "${{github.event.pull_request.html_url}}"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
